# Generated by Django 2.1.1 on 2018-09-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180912_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='First_Name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Last_Name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='aaa@b.c', max_length=25),
            preserve_default=False,
        ),
    ]
