# Generated by Django 2.1.1 on 2018-09-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180913_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_content',
            field=models.TextField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
