# Generated by Django 2.1.1 on 2018-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180912_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default=None, height_field=300, null=True, upload_to='', width_field=300),
        ),
    ]
