# Generated by Django 2.1.1 on 2018-09-12 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180912_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
