# Generated by Django 2.1.1 on 2018-09-17 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 22, 51, 46, 147009), verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
