# Generated by Django 2.1.1 on 2018-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofile_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matric_number',
            field=models.CharField(default='U1720251K', max_length=20),
            preserve_default=False,
        ),
    ]
